### ISSUE TITLE
Pass arguments to lftp

### ISSUE THREAD

**Issue by ItsBasvanDam** [sebastianpopp/ftp-action#10]
Feature request:

Whilst using your package, I ran into an issue. I publish files to my ftp server, into a specific folder. However, the files that are already there are either overridden (if their name is the same as a new file) or they stay as they are, which hogs my storage.

That is why I have to delete all files from the target directory prior to transferring. Incidentally, lftp has a flag for this exact situation, namely the —delete flag.

Could the user be granted a property with which they could pass arguments to lftp, such as —delete?

Another solution is to make a boolean flag for the —delete flag specifically, which controls whether or not the —delete flag is added as an argument to lftp.

**Comment by Mozart409** [comment]
Yes this would be awesome :)
