### ISSUE TITLE
Upload contents of a directory to the root of the remote server

### ISSUE THREAD

**Issue by pilotkid** [sebastianpopp/ftp-action#11]
Hello, is it possible to upload the contents of a folder to the root directory of the server? 

For example, locally there is the `dist` directory that I want the contents of to become the contents of the FTP server

**Comment by sebastianpopp** [comment]
In the input parameters, you can just set `remoteDir: "."` or remove the option since `.` is the default.

**Comment by pilotkid** [comment]
@sebastianpopp Thank you, once I directly specified that it is `remoteDir:"."` it worked flawlessly. 

Thank you for your help, and for developing this awesome plugin.
