### ISSUE TITLE
Question: Upload only Files affected in Push that starts Action

### ISSUE THREAD

**Issue by Galileon-venta** [sebastianpopp/ftp-action#14]
Is there a way to only upload the updated files? I've got a lot of pictures that are always reuploaded which causes the pipeline to take half an hour.

**Comment by sebastianpopp** [comment]
Are your pictures commited to your repo or do you generate them inside your workflow? You can take a look at [git-ftp](https://github.com/git-ftp/git-ftp) and my [git-ftp-action](https://github.com/sebastianpopp/git-ftp-action).

**Comment by Galileon-venta** [comment]
Your git-ftp-action did it for me; Thanks a lot!
