### ISSUE TITLE
left only overwrites the same remote file over and over again

### ISSUE THREAD

**Issue by emign** [sebastianpopp/ftp-action#2]
Hi,
I want to transfer my Kdoc Dokka Documentation after creating it from a gradle task.
The problem is, that lftp does NOT upload the whole folder, instead it overwrites the same file over and over again:

![Nov-29-2019 20-09-31](https://user-images.githubusercontent.com/5278352/69886826-2d4bb080-12e4-11ea-8a6c-d8c879219bfe.gif)

The upload action runs for about 15 minutes doing the overwriting for the whole time and then quits with:

> mirror: index-outline.html: Fatal error: max-retries exceeded

I just want to completely upload the local directory, deleting everything that is in the remote-dir

**Comment by sebastianpopp** [comment]
did you try running the command from your local environment?

**Comment by emign** [comment]
It was a certificate error. 
I switched to scp
