### ISSUE TITLE
Uploading only the file that was pushed

### ISSUE THREAD

**Issue by pgschr** [sebastianpopp/ftp-action#3]
Is there a way to FTP _only_ the file that was changed in GiHub (pushed from the GitHub client), instead of the complete folder?

Thanks

**Comment by sebastianpopp** [comment]
I don't think that's something you can achieve with this action, but take a look at [git-ftp](https://github.com/git-ftp/git-ftp) and my [git-ftp-action](https://github.com/sebastianpopp/git-ftp-action). I think that might me what you're looking for.
