### ISSUE TITLE
This action just freezes for ever after first time it worked.

### ISSUE THREAD

**Issue by billw2012** [sebastianpopp/ftp-action#4]
First time I used this it worked fine, but every time it ran since it just hangs forever with no output:
https://github.com/Sparker95/Vindicta/runs/427536651?check_suite_focus=true
![image](https://user-images.githubusercontent.com/1453936/73845474-a43c8280-481a-11ea-8f3f-65b641ba4cc9.png)

Your other ftp action works, but I just want to upload some files to an ftp server, not sync a git repo.

**Comment by billw2012** [comment]
On reflection this *could* be because the remote file is locked, however I would expect some output or abort if that is the case, not just hanging forever.

**Comment by sebastianpopp** [comment]
I haven't really tested it for edge cases like that. You could check the lftp manual for that as this action is only [one command](https://github.com/sebastianpopp/ftp-action/blob/60e94deadd99df7b2cabda98b190e03639e0aa99/entrypoint.sh#L3). I'd be happy to accept a pull request if you're able to handle this better.
